/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FilterModel, SelectOptions } from "./components/app-about/models";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AboutFilter {
        "filter": FilterModel;
        "subfilers": FilterModel[];
    }
    interface AboutSubFilter {
        "filter": FilterModel;
    }
    interface AppAbout {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAboutFilterElement extends Components.AboutFilter, HTMLStencilElement {
    }
    var HTMLAboutFilterElement: {
        prototype: HTMLAboutFilterElement;
        new (): HTMLAboutFilterElement;
    };
    interface HTMLAboutSubFilterElement extends Components.AboutSubFilter, HTMLStencilElement {
    }
    var HTMLAboutSubFilterElement: {
        prototype: HTMLAboutSubFilterElement;
        new (): HTMLAboutSubFilterElement;
    };
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "about-filter": HTMLAboutFilterElement;
        "about-sub-filter": HTMLAboutSubFilterElement;
        "app-about": HTMLAppAboutElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AboutFilter {
        "filter"?: FilterModel;
        "onFilterChange"?: (event: CustomEvent<SelectOptions[]>) => void;
        "subfilers"?: FilterModel[];
    }
    interface AboutSubFilter {
        "filter"?: FilterModel;
        "onSubFilterChange"?: (event: CustomEvent<{selectedValues:SelectOptions[],index:number}>) => void;
    }
    interface AppAbout {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "about-filter": AboutFilter;
        "about-sub-filter": AboutSubFilter;
        "app-about": AppAbout;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-filter": LocalJSX.AboutFilter & JSXBase.HTMLAttributes<HTMLAboutFilterElement>;
            "about-sub-filter": LocalJSX.AboutSubFilter & JSXBase.HTMLAttributes<HTMLAboutSubFilterElement>;
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
